data:
  train_file: "data/train.txt"
  test_file: "data/test_without_label.txt"
  val_size: 0.125
  img_dir: "data/data"
  txt_dir: "data/data"
  seed: 42
  imbalance_method: "weighted"

training:
  batch_size: 64
  num_epochs: 10
  learning_rate: 1e-4
  weight_decay: 1e-2
  clip_model: "ViT-L/14@336px"
  device: "cuda"
  save_dir: "checkpoints"
  fusion: "concat"
  ablation: "none"
  log_dir: "logs"
  plot_dir: "plots"
